import SwiftUI
import SwiftData

/// Builds a one-page monthly PDF summary (spend by category, vs budget, vs last month)
/// using `ImageRenderer`. Rendered on-device; shareable/exportable.
@MainActor
enum ReportBuilder {

    struct ReportData {
        let monthTitle: String
        let expense: Decimal
        let income: Decimal
        let prevExpense: Decimal
        let slices: [AnalyticsData.CategorySlice]
        let budgetLines: [(name: String, spent: Decimal, limit: Decimal)]
    }

    static func gather(monthKey: Int, in context: ModelContext) -> ReportData {
        let (expense, income) = AnalyticsData.monthTotals(monthKey: monthKey, in: context)
        let (prevExpense, _) = AnalyticsData.monthTotals(monthKey: DateKeys.monthKey(monthKey, offsetBy: -1), in: context)
        let slices = AnalyticsData.categorySlices(monthKey: monthKey, in: context)
        let cats = Dictionary(((try? context.fetch(FetchDescriptor<Category>())) ?? []).map { ($0.id, $0.name) }, uniquingKeysWith: { a, _ in a })
        let budgets = (try? context.fetch(FetchDescriptor<CategoryBudget>())) ?? []
        let budgetLines = budgets.map { b -> (String, Decimal, Decimal) in
            let spent = slices.first { $0.categoryID == b.categoryID }?.amountKZT ?? 0
            return (cats[b.categoryID] ?? b.categoryID, spent, b.limitKZT)
        }
        return ReportData(monthTitle: DateKeys.startOfMonth(monthKey: monthKey).formatted(.dateTime.month(.wide).year()),
                          expense: expense, income: income, prevExpense: prevExpense,
                          slices: slices, budgetLines: budgetLines)
    }

    static func makePDF(monthKey: Int, in context: ModelContext) -> Data? {
        let data = gather(monthKey: monthKey, in: context)
        let renderer = ImageRenderer(content: MonthlyReportView(data: data).frame(width: 612))
        renderer.scale = 2
        let pdfData = NSMutableData()
        renderer.render { size, renderInContext in
            var box = CGRect(x: 0, y: 0, width: 612, height: max(792, size.height))
            guard let consumer = CGDataConsumer(data: pdfData as CFMutableData),
                  let pdf = CGContext(consumer: consumer, mediaBox: &box, nil) else { return }
            pdf.beginPDFPage(nil)
            renderInContext(pdf)
            pdf.endPDFPage()
            pdf.closePDF()
        }
        return pdfData as Data
    }
}

/// Presentation-only monthly report (fed precomputed data so it renders off the live store).
struct MonthlyReportView: View {
    let data: ReportBuilder.ReportData

    private var momText: String {
        guard data.prevExpense > 0 else { return "—" }
        let change = (data.expense.doubleValue - data.prevExpense.doubleValue) / data.prevExpense.doubleValue * 100
        return String(format: "%@%.0f%% vs last month", change >= 0 ? "+" : "", change)
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 18) {
            VStack(alignment: .leading, spacing: 2) {
                Text("Monthly Report").font(.title.bold())
                Text(data.monthTitle).font(.title3).foregroundStyle(.secondary)
            }
            HStack(spacing: 24) {
                metric("Spent", data.expense, .primary)
                metric("Income", data.income, .green)
                metric("Net", data.income - data.expense, data.income - data.expense >= 0 ? .green : .red)
            }
            Text(momText).font(.subheadline).foregroundStyle(.secondary)

            Divider()
            Text("Spending by category").font(.headline)
            ForEach(data.slices) { s in
                HStack {
                    Circle().fill(Color(hex: s.colorHex)).frame(width: 10, height: 10)
                    Text("\(s.emoji) \(s.name)")
                    Spacer()
                    Text(CurrencyFormatter.kzt(s.amountKZT))
                }.font(.subheadline)
            }

            if !data.budgetLines.isEmpty {
                Divider()
                Text("Budgets").font(.headline)
                ForEach(data.budgetLines, id: \.name) { line in
                    HStack {
                        Text(line.name)
                        Spacer()
                        Text("\(CurrencyFormatter.kzt(line.spent)) / \(CurrencyFormatter.kzt(line.limit))")
                            .foregroundStyle(line.spent > line.limit ? .red : .primary)
                    }.font(.subheadline)
                }
            }
            Spacer()
            Text("Generated by Qazyna · \(Date().formatted(date: .abbreviated, time: .omitted))")
                .font(.caption2).foregroundStyle(.secondary)
        }
        .padding(32)
        .frame(width: 612, alignment: .topLeading)
        .background(Color.white)
        .environment(\.colorScheme, .light)
    }

    private func metric(_ title: String, _ value: Decimal, _ color: Color) -> some View {
        VStack(alignment: .leading, spacing: 2) {
            Text(title).font(.caption).foregroundStyle(.secondary)
            Text(CurrencyFormatter.kzt(value)).font(.title3.weight(.bold)).foregroundStyle(color)
        }
    }
}
